### ISSUE TITLE
go.php?to=admin-encryption is a 404

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#4307]
Seen with server 10.8.0 and encryption-1.5.1 while testing files_primary_s3-1.1.3-rc2

* Visit the admin settings, click encryption
* The first line has a _i_ for more information
* Click there, the link is a 404
![image](https://user-images.githubusercontent.com/1108546/142615356-7a1fbbcc-f02c-4c99-92be-229bbd84a7c7.png)

* it resolves to https://doc.owncloud.com/server/10.8/admin_manual/configuration/files/encryption_configuration.html which does not exist.

Expected behaviour:
 * https://doc.owncloud.com/server/10.8/admin_manual/configuration/files/encryption/encryption_configuration.html which does exist.

**Comment by mmattel** [comment]
@xoxys what is the process to fix the link in the go script?

**Comment by xoxys** [comment]
Dont need to be fixed on the server side, just add a working page alias.

**Comment by mmattel** [comment]
> Dont need to be fixed on the server side, just add a working page alias.

Imho the go part script should be fixed as this points to the wrong location, that is what the script is for.
And in any case, I would like to know the process how to fix that. Mind to tell me how?

**Comment by xoxys** [comment]
I told you. You can not, notify our team and still... This was working before you changed the content structure. So please use page aliases.

**Comment by xoxys** [comment]
@mmattel The page alias is still not working..... https://doc.owncloud.com/server/10.8/admin_manual/configuration/files/encryption_configuration.html still ends up in a 404.

**Comment by xoxys** [comment]
There is a comma missing in your PR

**Comment by xoxys** [comment]
Syntax was fixed, verified the Link, works now.

**Comment by mmattel** [comment]
Sorry for the typo... 🤦‍♂️
